"""add trailer_src

Revision ID: a741105c965f
Revises: 2ad8b066ad76
Create Date: 2026-05-31 12:17:22.268781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a741105c965f'
down_revision: Union[str, Sequence[str], None] = '2ad8b066ad76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('trailer_src', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'trailer_src')
    # ### end Alembic commands ###
